version: '3'
services:
  web:
    image: bigpapoo/r5a05-nginx
    container_name: application
    build: 
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"
    networks:
      - rezo_api_web

  db:
    image: bigpapoo/r5a05-postgres
    container_name: database
    ports: 
      - "5601:5432"
    volumes:
      - data:/var/www/html
    networks:
      - rezo_api_database
    environment:
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'koh_lanta_db'
    
  api:
    build: 
      context: .
      dockerfile: Dockerfile-api
    container_name: api
    ports: 
    - "8081:8000"
    depends_on:
      - db
    networks:
      - rezo_api_database
      - rezo_api_web

volumes:
  data:
  
networks:
  rezo_api_database:
  rezo_api_web: