FROM bigpapoo/r5a05-node:latest as build-stage

WORKDIR /app
COPY . /app

RUN npm install
RUN npm run build

FROM bigpapoo/r5a05-nginx:latest
RUN rm /usr/share/nginx/html/*

COPY --from=build-stage /app/dist /usr/share/nginx/html/