version: '3'
services:
  web:
    container_name: application
    build: 
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "3100:80"
    networks:
      - frontend

  db:
    image: bigpapoo/r5a05-postgres
    container_name: database
    ports: 
      - "5601:5432"
    volumes:
      - data:/var/www/html
      # - ./src/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'koh_lanta_db'
    
  api:
    build: 
      context: .
      dockerfile: Dockerfile-api
    container_name: api
    ports: 
    - "3200:8000"
    depends_on:
      - db
    networks:
      - backend
      - frontend

volumes:
  data:
  
networks:
  backend:
  frontend: