FROM bigpapoo/r5a05-node:latest as build-stage

WORKDIR /app

COPY package.*json ./
RUN npm install
COPY . .
RUN npm run build

FROM bigpapoo/r5a05-nginx:latest
RUN rm /usr/share/nginx/html/*.html

COPY --from=build-stage build /usr/share/nginx/html
